### ISSUE TITLE
Add a 2x Mode

### ISSUE THREAD

**Issue by torch2424** [torch2424/vaporBoy#113]
Would make testing / playing Pokemon much easier haha 😂

**Comment by Kcorab** [comment]
Hi Aaron,
I know you are very busy but is there a change to get this feature soon? =)

**Comment by torch2424** [comment]
Hello @Kcorab ! :smile: 

So I have not yet, but you can still do this (though, not very convenient haha!):

Control Panel > Options > Performance > Maximum Framerate

This controls how fast the game will allow itself to run :smile: So 60 means runs 60 frames per second (1x), so to do 2x, you could set it to 120. But this is definitely not the best experience :upside_down_face: 

But it's not hard to implement at all :smile: If you don't mind, feel free to keep reminding me and I can add it in :smile: I'll try tommorrow!
