### ISSUE TITLE
Broken direction control

### ISSUE THREAD

**Issue by Kcorab** [torch2424/vaporBoy#115]
The following issue appears on:

OS: iOS 12.3.1
iPhone SE
Browsers: Safari (incl. PWA), Firefox (17.3), Chrome (75.0.3770.103)
Roms: Pokémon Yellow, Zelda Links Awakening

After few minutes of playing the direction control is absolutely broken. Especially in full size mode.

**Comment by torch2424** [comment]
@Kcorab Thank you very much for filing this bug! Will investigate this, and try and get it fixed :smile:

**Comment by Kcorab** [comment]
This bug still exist on iOS 13.3.

Disallowing the Viewport zoom-in is may enough for solving this unusual behaviour. Caution: Disable zoom-in for safari browser could be difficult.

**Comment by torch2424** [comment]
Oh snap, this fell through the crack 😲 I do remember I did some control fixes in the past for iOS, so but thank you SOOOOO much for bumping this @Kcorab 

I just got paid from work today, I'll buy and iOS 13 Iphone (been on my TODO list for a long time). and try to fix this! Keeping this in an open tab to get done 😄

**Comment by Kcorab** [comment]
My device is still the iPhone SE and the virtual game pad bug exist on Vaporboy (https://vaporboy.net/) 0.2.0.

**Comment by torch2424** [comment]
@Kcorab For sure, thanks for letting me know!

Just ordered the latest iPod Touch, so I can investigate this:

![Screenshot from 2020-01-18 22-37-02](https://user-images.githubusercontent.com/1448289/72676176-253a0280-3a43-11ea-99d8-f8cbe74ddd41.png)

So hopefully sometime next week I can debug and fix :smile: :+1:

**Comment by Kcorab** [comment]
@torch2424 
I am impressed how ambitious you are. Be careful, the iPod may not get iOS13.

**Comment by torch2424** [comment]
@Kcorab Thanks! Yeah I bought the latest generation, so it should get the latest iOS13 😄 Should be coming in the mail today, so I'll go ahead and try things out

**Comment by torch2424** [comment]
So The iPod Touch came, and I tried it out, and it all worked fine?

Here are multiple screenshots, and I played for like 10 minutes:

![IMG_0004](https://user-images.githubusercontent.com/1448289/72960459-a4d91180-3d62-11ea-9b0f-f9cfbddbd57f.PNG)
![IMG_0003](https://user-images.githubusercontent.com/1448289/72960460-a4d91180-3d62-11ea-8159-09f0cb8929e1.PNG)
![IMG_0002](https://user-images.githubusercontent.com/1448289/72960461-a4d91180-3d62-11ea-8c8b-e6b08cfeeeb1.PNG)
![IMG_0001](https://user-images.githubusercontent.com/1448289/72960462-a4d91180-3d62-11ea-8f61-1623c1f15381.PNG)
![IMG_0005](https://user-images.githubusercontent.com/1448289/72960463-a4d91180-3d62-11ea-8fe5-665c0ff6509e.PNG)

Not sure If I am doing something wrong? I do want to disable the zoom though, but it doesn't fire when I'm playing usually which is nice 🤔

**Comment by Kcorab** [comment]
@torch2424
Please try it under PWA mode and also try LoZ: Links Awakening.

**Comment by torch2424** [comment]
@Kcorab My bad was super duper sick yesterday, but I'll try that after work today 😄

**Comment by torch2424** [comment]
So I tested it out, specifically in PWA mode, and with LoZ: Links Awakening, and it still worked fine? I played for like 20 minutes. All the way to getting the tail key. Even tried to like DogHouse glitch for like 5 minutes. But yeah still worked?

Here's a video before I stopped playing: https://photos.app.goo.gl/wxi7z9ZdkdAc8z5AA

All the stumbling with the controls is from me playing with one hand, and trying to record with the other :joy: But I swear for the other 18 minutes, I was moving around just fine :smile:

**Comment by Kcorab** [comment]
Wow, it works on your machine. :thinking: 

Please try to rotate and maximize the app. Then the direction control will definitely go broken. :smiling_imp:

**Comment by torch2424** [comment]
@Kcorab Awesome! I'll try that tonight 😄

**Comment by torch2424** [comment]
@Kcorab My bad! I recently had a bunch of job stuff to handle and stuff, but definitely going to try this ASAP. Probably tommorrow morning, if not, the day after :smile: :+1:

**Comment by torch2424** [comment]
Oh yay! I can finally reproduce it haha! @Kcorab Yeah going into "expanded" mode, and rotating broke the controls. Thankfully, I think I have an idea on how to fix this easily :smile: 

So I'm currently in between jobs, so I'll go ahead and keep this on my TODO list, and try to fix it tommorrow :+1:

**Comment by Kcorab** [comment]
@torch2424 
Yeah! 😃 But keep in mind that the direction control brokes only on Apple devices (Safari). It seems to be a specific bug.

**Comment by torch2424** [comment]
@Kcorab I did some more research, and it seems to be all browsers for iOS (Chrome, FireFox, and Safari). So it's not just a safari issue. I'm trying to think of an easy way I can debug this :joy:
