### ISSUE TITLE
Can you play two games at once/will it be implemented?

### ISSUE THREAD

**Issue by MarcellusIsHere** [torch2424/vaporBoy#129]
I wanted to know if it is possible to connect to two games at once, or if it will ever be implemented? For example, if you're playing a multiplayer game, you can have two windows open and connect to the game. Or like trading in Pokémon. Is it even possible? Thank you for your time!

**Comment by torch2424** [comment]
Hello @MarcellusIsHere ! :smile: 

So it is something I had looked into for our downstream dependancy, WasmBoy: https://github.com/torch2424/wasmboy/issues/34

But I just haven't had the time to implement it :cry: But I've been really missing working on this project, so I may try to pick it up next time I'm on work vacation :)

**Comment by MarcellusIsHere** [comment]
I see. Well, thank you for the quick answer. I understand.
